name: Deploy AI-KYC Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.HOST }}
        if_key_exists: ignore
        
    - name: Deploy Code
      run: |
        echo ${{ secrets.HOST }} > id_rsa && cat id_rsa
#        sudo systemctl daemon-reload
#        sudo systemctl enable ai-kyc.service
#        sudo systemctl restart ai-kyc.service
